[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'mkdir -p storage/framework/{sessions,views,cache} storage/logs bootstrap/cache',
    'chmod -R 755 storage bootstrap/cache'
]

[start]
cmd = 'bash start.sh'